nome: Gerar Dados


sobre:

agendamento: # executado a cada 12 horas

-cron: "* */12 * * *"

fluxo de trabalho_dispatch:

empregos:

construir:

nome: Jobs para atualizar dados

executado: ubuntu-mais recente

passos:

# Animação de cobra

- usos: Platane/snk@master

id: cobra-gif

com:

github_user_name: agneloobruno

svg_out_path: dist/github-contribution-grid-snake.svg


- usa: crazy-max/ghaction-github-pages@v2.1.3

com:

target_branch: saída

build_dir: dist

ambiente:

GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


